version: "3.8"

services:
  web:
    image: ${IMAGE}
    networks:
      - traefik-public
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.services.web.loadbalancer.server.port=80
        - traefik.http.routers.web.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.web.entrypoints=websecure
        - traefik.http.routers.web.tls=true
        - traefik.http.routers.web.tls.certresolver=leresolver

networks:
  traefik-public:
    external: true
