version: "3.8"

services:
  webfront-fraudai:
    image: ${IMAGE}
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.http.services.webfront-fraudai.loadbalancer.server.port=80
        - traefik.http.routers.webfront-fraudai.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.webfront-fraudai.entrypoints=websecure
        - traefik.http.routers.webfront-fraudai.tls=true
        - traefik.http.routers.webfront-fraudai.tls.certresolver=leresolver

networks:
  traefik-public:
    external: true
